## DATA SET: 

#### AI Global Index

CSV file from:
https://www.kaggle.com/datasets/katerynameleshenko/ai-index/data

#### GDP per country

https://www.worldometers.info/gdp/gdp-by-country/

In [1]:
pip install pandas

Requirement already satisfied: pandas in /opt/anaconda3/lib/python3.11/site-packages (2.1.4)
Requirement already satisfied: numpy<2,>=1.23.2 in /opt/anaconda3/lib/python3.11/site-packages (from pandas) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /opt/anaconda3/lib/python3.11/site-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /opt/anaconda3/lib/python3.11/site-packages (from pandas) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in /opt/anaconda3/lib/python3.11/site-packages (from pandas) (2023.3)
Requirement already satisfied: six>=1.5 in /opt/anaconda3/lib/python3.11/site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Note: you may need to restart the kernel to use updated packages.

In [2]:
import pandas as pd

In [3]:
path1 = "AI_index_db.csv"
df_ai = pd.read_csv(path1)
pd.set_option('display.max_columns', None)
df_ai

,Country,Talent,Infrastructure,Operating Environment,Research,Development,Government Strategy,Commercial,Total score,Region,Cluster,Income group,Political regime
0,United States of America,100.00,94.02,64.56,100.00,100.00,77.39,100.00,100.00,Americas,Power players,High,Liberal democracy
1,China,16.51,100.00,91.57,71.42,79.97,94.87,44.02,62.92,Asia-Pacific,Power players,Upper middle,Closed autocracy
2,United Kingdom,39.65,71.43,74.65,36.50,25.03,82.82,18.91,40.93,Europe,Traditional champions,High,Liberal democracy
3,Canada,31.28,77.05,93.94,30.67,25.78,100.00,14.88,40.19,Americas,Traditional champions,High,Liberal democracy
4,Israel,35.76,67.58,82.44,32.63,27.96,43.91,27.33,39.89,Middle East,Rising stars,High,Liberal democracy
...,...,...,...,...,...,...,...,...,...,...,...,...,...
57,Sri Lanka,6.27,34.64,35.79,0.12,0.95,35.57,0.09,6.62,Asia-Pacific,Nascent,Lower middle,Electoral democracy
58,Egypt,1.11,38.84,0.00,2.08,1.54,68.72,0.31,4.83,Middle East,Nascent,Lower middle,Electoral autocracy
59,Kenya,0.75,14.11,29.84,0.07,12.15,7.75,0.31,2.30,Africa,Nascent,Lower middle,Electoral autocracy
60,Nigeria,2.74,0.00,50.10,0.45,2.06,7.75,0.33,1.38,Africa,Nascent,Lower middle,Electoral autocracy
61,Pakistan,8.00,2.43,12.48,2.17,1.09,13.92,0.27,0.00,Asia-Pacific,Nascent,Lower middle,Electoral autocracy

In [4]:
df_ai.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 62 entries, 0 to 61
Data columns (total 13 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Country                62 non-null     object
 1   Talent                 62 non-null     float64
 2   Infrastructure         62 non-null     float64
 3   Operating Environment  62 non-null     float64
 4   Research               62 non-null     float64
 5   Development            62 non-null     float64
 6   Government Strategy    62 non-null     float64
 7   Commercial             62 non-null     float64
 8   Total score            62 non-null     float64
 9   Region                 62 non-null     object
 10  Cluster                62 non-null     object
 11  Income group           62 non-null     object
 12  Political regime       62 non-null     object
dtypes: float64(8), object(5)
memory usage: 6.4+ KB

In [5]:
df_ai.isnull().any()

Country                  False
Talent                   False
Infrastructure           False
Operating Environment    False
Research                 False
Development              False
Government Strategy      False
Commercial               False
Total score              False
Region                   False
Cluster                  False
Income group             False
Political regime         False
dtype: bool

In [6]:
df_ai.duplicated().sum()

0

In [9]:
df_ai["Country"].unique()

array(['United States of America', 'China', 'United Kingdom', 'Canada',
       'Israel', 'Singapore', 'South Korea', 'The Netherlands', 'Germany',
       'France', 'Australia', 'Ireland', 'Finland', 'Denmark',
       'Luxembourg', 'Japan', 'India', 'Switzerland', 'Sweden',
       'Hong Kong', 'Spain', 'Austria', 'Estonia', 'Taiwan', 'Norway',
       'Saudi Arabia', 'Belgium', 'Poland', 'Slovenia', 'New Zealand',
       'Italy', 'Russia', 'Malta', 'United Arab Emirates', 'Portugal',
       'Czech Republic', 'Iceland', 'Lithuania', 'Brazil', 'Greece',
       'Slovakia', 'Hungary', 'Malaysia', 'Mexico', 'Chile', 'Argentina',
       'Qatar', 'Turkey', 'Colombia', 'Uruguay', 'Bahrain', 'Vietnam',
       'Indonesia', 'Tunisia', 'South Africa', 'Morocco', 'Armenia',
       'Sri Lanka', 'Egypt', 'Kenya', 'Nigeria', 'Pakistan'], dtype=object)

## GDP per country (WORLD BANK GROUP API)